version: '3'

services:
  frontend:
    restart: always
    build: ./frontend
    volumes:
      - /app/frontend/node_modules
      - ./frontend:/app/frontend
    ports:
      - '3000:3000'
  api:
    restart: always
    build: ./api
    volumes:
      - ./api:/app/api
    ports:
      - '5000:5000'
  mongo:
    restart: always
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: a-strong-password
    volumes:
      - mongo_db_data:/data/db
  mongo-express:
    restart: always
    image: mongo-express
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: a-strong-password
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
volumes:
  mongo_db_data:
