version: '3'

services:
  frontend:
    restart: always
    build: ./frontend
    volumes:
      - /app/frontend/node_modules
      - ./frontend:/app/frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - '3001:3000'
  api:
    restart: always
    build: ./api
    volumes:
      - ./api:/app/api
    ports:
      - '5000:5000'
